unlock:
  target:
      entity:
        domain: lock
  fields:
    time_secs:
      required: false
      selector:
        number:
          min: 0
          max: 7200
          unit_of_measurement: seconds

area_arm:
  target:
    entity:
      domain: alarm_control_panel
  fields:
    exit_delay:
      required: false
      selector:
        boolean:
    seal_check:
      required: false
      selector:
        boolean:
    code:
      required: false
      selector:
        text:
